### ISSUE TITLE
how to derive the require paths?

### ISSUE THREAD

**Issue by dcsan** [markoshust/meteor-material-ui#12]
I'm trying to include a menu. From the mui docs
http://www.material-ui.com/#/components/menus

``` js
let Menu = require('material-ui/lib/menus/menu');
let MenuItem = require('material-ui/lib/menus/menu-item');
let MenuDivider = require('material-ui/lib/menus/menu-divider');
```

how does that translate into use with this package?
from your example:

```
const { AppBar, IconButton, IconMenu, LeftNav } = mui;
const { MenuItem } = mui.Menus;
```

so

```
material-ui/lib/menus/menu-item = mui.Menus
```

not sure if that mapping is consistent

```
material-ui/lib/menus/menu = mui.Menu   ???
```

edit: ok so this works, but its a bit trial and error to work out

```
const { Menu } = mui;
const { MenuItem } = mui.Menus;
```

I don't quite follow how you define a bunch of things to be `mui`
`const { AppBar, IconButton, IconMenu, LeftNav } = mui;`  and now add Menu to that list...

is there some extra layer of indirection within this meteor package whenever `mui.X()` method is called?

I guess all defines are just "one level up the hierarchy" from the object you actually require?

**Comment by markshust** [comment]
Please see this browserify file (https://github.com/markoshust/meteor-material-ui/blob/master/app.browserify.js), needed to add these to get a better correlation to the material-ui package and meteor. The menu code in menus/menu is the more updated code in the material-ui lib.

For the menus, you want to define them as such:

```
const { AppBar, IconButton, IconMenu, LeftNav } = mui;
const { Menu, MenuItem } = mui.Menus
```

All of this should be standard material-ui format, nothing was changed from that lib. Just some helpers written to correctly call things in meteor.

**Comment by dcsan** [comment]
thanks for this.

btw they changed the menus code significantly in the current 0.14-rc2
there are no menuItems any more as part of menu, just `<MenuItem/>` as a seprate composable entity.

I forked and updated your package,
https://github.com/dcsan/meteor-material-ui/blob/master/package.js#L14

and made a sample repo here of how to use the new menu stuff
https://github.com/dcsan/react-hot/blob/master/app/client/layouts/MainLayout.jsx

demo
http://react-hot.meteor.com/

i can send a PR but its a breaking change upstream in material-ui

**Comment by markshust** [comment]
Yes, I'm aware. The `menuItem` prop is unneeded as you can just pass in the children with those menuItems. I had a ticket somewhere with material-ui on this, but forgot where it was. Anyway, the updates are the preferred way to do this anyways.

Thanks for providing the fork. Since it's a major version bump (13 to 14), breaking changes are just fine. I'll wait until it hits an official 0.14 release though to issue a version bump for this package.

Hope this is all over with in Meteor 1.3 and I can just discontinue all of these odd npm wrappers ;)
