### ISSUE TITLE
Hang on building in Meteor 1.3.beta4

### ISSUE THREAD

**Issue by dagatsoin** [markoshust/meteor-material-ui#16]
Hello. I am trying to use it with Meteor 1.3.beta4 but it hangs at building time and I need to force killed the Node instance.

**Comment by markshust** [comment]
I wouldn't use this package in 1.3. Really 1.2 is the last version all of these npm wrappers will most likely support.

In 1.3, you want to add material-ui directly to your package.json file, or use the new Npm.depends within a package. Goodbye npm wrappers! Yay!

**Comment by dagatsoin** [comment]
Indeed I did install throw package.json but I get stuck with a dual loading of react.

```
Warning: React can't find the root component node for data-reactid value `.0.0.0.0`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
```

I think MaterialUI imports react as well and I don't know how to prevent that.

**Comment by markshust** [comment]
This isn't related to this package -- you'll need to file a ticket/issue at https://github.com/meteor/meteor/issues/5788#issuecomment-173228949
