### ISSUE TITLE
Colors is not defined

### ISSUE THREAD

**Issue by VinceBT** [markoshust/meteor-material-ui#2]
Hello :)

I wanna use the MUI Colors for Avatars but I cant find what to import.
I have this example : 

``` jsx
<Avatar
   color={Colors.deepOrange300}
   backgroundColor={Colors.purple500}>
   {list.name.toUpperCase().charAt(0)}
</Avatar>
```

And in the console it says : 

`Uncaught ReferenceError: Colors is not defined`

Thanks by advance for any help :)
Thank you again for this great package !

**Comment by markshust** [comment]
I didn't setup Colors yet. I'll be doing a lot of material-ui work tonight, and will add this functionality in. I did a very barebones package setup, with the expectation of these types of issues :)

**Comment by markshust** [comment]
Colors are in the `mui.Styles` object already. I added this to the upcoming README.

So you can call it like so:

`mui.Styles.Colors.deepOrange300`

**Comment by VinceBT** [comment]
Thank you :) !
