### ISSUE TITLE
Static Import of components

### ISSUE THREAD

**Issue by VinceBT** [markoshust/meteor-material-ui#5]
I am trying to import the components the static way in order to not write mui.AppBar for example each time so I wrote : 

``` jsx
const { AppCanvas, AppBar, Avatar, Checkbox, CircularProgress, DatePicker, Dialog, FlatButton, FloatingActionButton, FontIcon, IconMenu, IconButton, LeftNav, List, ListItem, ListDivider, RaisedButton, Tabs, Tab, TextField , SvgIcon } = mui;
const { MenuItem } = mui.Menus;
const { ContentAdd, NavigationMoreVert, ToggleStar } = mui.Icons;
const { Colors } = mui.Styles;
```

But the console says `TypeError : Cannot read property 'AppCanvas' of undefined`.
These lines were perfectly wokring before the last update :(

Can you help ?

**Comment by markshust** [comment]
I don't see `AppCanvas` listed as a possible component http://material-ui.com/#/components/ -- only going to support components in that library, and only ones with documentation on their site on how to implement. You'll probably need to open up an issue with material-ui.com.

**Comment by VinceBT** [comment]
The problem didnt come from the AppCanvas component.
It is just the static import that I do which does not work anymore and I can't figure out why.
