### ISSUE TITLE
[Error] mui is not defined

### ISSUE THREAD

**Issue by VinceBT** [markoshust/meteor-material-ui#8]
As I was testing your example I wrote this in a test project : 

``` jsx
const { AppBar, IconButton, IconMenu, LeftNav } = mui;
const { MenuItem } = mui.Menus;
const { NavigationMoreVert } = mui.SvgIcons;
const Styles = mui.Styles;
const Colors = Styles.Colors;
```

And I get the error that the mui object is null so it doesnt start anymore.
This is the reason of the other issue : https://github.com/markoshust/meteor-material-ui/issues/5

**Comment by markshust** [comment]
Do you have the module installed? ha.

Try meteor update. mui should definitely be available.

**Comment by VinceBT** [comment]
Yes I have :(

This is the package list from the directory : 

![f3540ea8b5792659339afeb75936e9ba](https://cloud.githubusercontent.com/assets/1362505/11043075/34964020-871b-11e5-9094-27a4cec498d0.png)

**Comment by markshust** [comment]
are you loading this on the client or the server?

**Comment by VinceBT** [comment]
I want to load this on the client but how do I know which it is ?

**Comment by markshust** [comment]
Please see example app at https://github.com/meteor/react-packages/tree/devel/examples/material-ui-leaderboard

Everything seems to be working correctly within that meteor app. So you may want to check that out, run it, then compare it to the install you are working with to see what is going on with your setup.

I'm unable to replicate this, so I'm closing this ticket out.

**Comment by VinceBT** [comment]
I moved all of the files to a client folder as your did in your repo and now it works ! Thanks
